[package]
name = "transactions-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
csv = "1.4.0"
fastnum = { version = "0.7.4", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
